config/routes.rb
Chatid::Application.routes.draw do
  get "search/index"

  resources :retailers

  resources :companies do
  	get 'page/:page', :action => :index, :on => :collection
  end

  resources :analytics, :action => :index
  resources :search, :action => :index
  

end

app/models/company.rb
class Company
  include Mongoid::Document
  field :name
  field :domain
  field :qrank
  field :arank
  field :server_location
  field :deepdive
  field :chat
  field :is_brand
  field :retailers
  field :social
 # paginates_per 100

  named_scope :arank_exists,	where(:arank.gt => -1)
  named_scope :qrank_exists,    where(:qrank.gt => -1)
  
	
  FILTERS = [
	{:scope => "all", :label => "All"},
	{:scope => "arank_exists", :label => "Valid Arank"},
	{:scope => "qrank_exists", :label => "Valid Qrank"}	
  ]

  def self.search(search)
	if search and !search.eql?("")
	  #where("this.name.match(/#{search}/i) || (this.chat.match(/#{search}/i)")
	  where("
			this.name.match(/#{search}/i) || 
			this.chat.match(/#{search}/i) || 
			this.domain.match(/#{search}/i)
		") 
	else
	  scoped
	end
  end

end

app/models/retailer.rb
class Retailer
  include Mongoid::Document
  field :name
  field :url
  field :brands
  key :name
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController

	def index
		@data = Hash.new
		Company.all.distinct(:chat).each do |chat|
			@data[chat] = Company.where(:chat => chat).count	
		end

		@fb_data = Hash.new
		@gp_data = Hash.new
		@tw_data = Hash.new
		Company.all.each do |company|
			company.social.each do |social|
				if social.include?("facebook")
					if @fb_data[company.chat].nil?
						@fb_data[company.chat] = 1
					else
						@fb_data[company.chat] += 1
					end
				end
				if social.include?("google")
					if @gp_data[company.chat].nil?
						@gp_data[company.chat] = 1
					else
						@gp_data[company.chat] += 1
					end
				end
				if social.include?("twitter")
					if @tw_data[company.chat].nil?
						@tw_data[company.chat] = 1
					else
						@tw_data[company.chat] += 1
					end
				end
			end
		end
		render
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
	
  helper_method :sort_column, :sort_direction

  def index
    @companies = Company.search(params[:search]).order_by([[sort_column, sort_direction]]).page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, :notice => 'Company was successfully created.' }
        format.json { render :json => @company, :status => :created, :location => @company }
      else
        format.html { render :action => "new" }
        format.json { render :json => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, :notice => 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @company.errors, status => :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
  
  def sort_column
    params[:sort] || "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController
  # GET /retailers
  # GET /retailers.json
  def index
    @retailers = Retailer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @retailers }
    end
  end

  # GET /retailers/1
  # GET /retailers/1.json
  def show
    @retailer = Retailer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @retailer }
    end
  end

  # GET /retailers/new
  # GET /retailers/new.json
  def new
    @retailer = Retailer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @retailer }
    end
  end

  # GET /retailers/1/edit
  def edit
    @retailer = Retailer.find(params[:id])
  end

  # POST /retailers
  # POST /retailers.json
  def create
    @retailer = Retailer.new(params[:retailer])

    respond_to do |format|
      if @retailer.save
        format.html { redirect_to @retailer, :notice => 'Retailer was successfully created.' }
        format.json { render :json => @retailer, :status => :created, :location => @retailer }
      else
        format.html { render :action => "new" }
        format.json { render :json => @retailer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /retailers/1
  # PUT /retailers/1.json
  def update
    @retailer = Retailer.find(params[:id])

    respond_to do |format|
      if @retailer.update_attributes(params[:retailer])
        format.html { redirect_to @retailer, :notice => 'Retailer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @retailer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /retailers/1
  # DELETE /retailers/1.json
  def destroy
    @retailer = Retailer.find(params[:id])
    @retailer.destroy

    respond_to do |format|
      format.html { redirect_to retailers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @results = ""
    @hitcount = ""
    if params[:search] and !params[:search].nil?
	    search_results = RDig.searcher.search(params[:search])
	    @results = search_results[:list]
	    @hitcount = search_results[:hitcount]
    end
  end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def sortable(column, title = nil)
	  title ||= column.titleize
	  css_class = column == sort_column ? "current #{sort_direction}" : nil
	  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	  link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
	end

	def select_tag_for_filter(model, nvpairs, params)
	  options = { :query => params[:query] }
	  _url = url_for(eval("#{model}_url(options)"))
	  _html = %{<label for="show">Show:</label><br />}
	  _html << %{<select name="show" id="show"}
	  _html << %{onchange="window.location='#{_url}' + '?show=' + this.value">}
	  nvpairs.each do |pair|
	    _html << %{<option value="#{pair[:scope]}"}
	    if params[:show] == pair[:scope] || ((params[:show].nil? || 
	params[:show].empty?) && pair[:scope] == "all")
	      _html << %{ selected="selected"}
	    end
	    _html << %{>#{pair[:label]}}
	    _html << %{</option>}
	  end
	  _html << %{</select>}
	  _html.html_safe
	end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/retailers_helper.rb
module RetailersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/analytics/index.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>Analytics</title>

		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script type="text/javascript">
var chart;
var fb_chart;
var gp_chart;
var tw_chart;
$(document).ready(function() {
	chart = new Highcharts.Chart({
		chart: {
			renderTo: 'chart',
			plotBackgroundColor: null,
			plotBorderWidth: null,
			plotShadow: false
		},
		title: {
			<% 
				count =0 
				@data.each_pair do |k,v|
 
			%>
			<% count += v %>
			<% end %>
			text: "Overall Usage by Chat company (Total: <%=count%>)"
		},
		tooltip: {
			formatter: function() {
				return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage) +' %';
			}
		},
		plotOptions: {
			pie: {
				allowPointSelect: true,
				cursor: 'pointer',
				dataLabels: {
					enabled: true,
					color: '#000000',
					connectorColor: '#000000',
					formatter: function() {
						return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage) +' %';
					}
				}
			}
		},
		series: [{
			type: 'pie',
			name: 'Browser share',
			data: [
				
				<% @data.each_pair do |k,v| %>
				 <%= "['#{k}', #{v}]," %>
				<% end %>
			]
		}]
	});
	fb_chart = new Highcharts.Chart({
		chart: {
			renderTo: 'fb_chart',
			plotBackgroundColor: null,
			plotBorderWidth: null,
			plotShadow: false
		},
		title: {
			<% 
				count =0 
				@fb_data.each_pair do |k,v|
 
			%>
			<% count += v %>
			<% end %>
			text: "Usage by Companies on Facebook (Total: <%=count%>)"
		},
		tooltip: {
			formatter: function() {
				return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage) +' %';
			}
		},
		plotOptions: {
			pie: {
				allowPointSelect: true,
				cursor: 'pointer',
				dataLabels: {
					enabled: true,
					color: '#000000',
					connectorColor: '#000000',
					formatter: function() {
						return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage) +' %';
					}
				}
			}
		},
		series: [{
			type: 'pie',
			name: 'Browser share',
			data: [
				
				<% @fb_data.each_pair do |k,v| %>
				 <%= "['#{k}', #{v}]," %>
				<% end %>
			]
		}]
	});
	gp_chart = new Highcharts.Chart({
		chart: {
			renderTo: 'gp_chart',
			plotBackgroundColor: null,
			plotBorderWidth: null,
			plotShadow: false
		},
		title: {
			<% 
				count =0 
				@gp_data.each_pair do |k,v|
 
			%>
			<% count += v %>
			<% end %>
			text: "Usage by Companies on G+ (Total: <%=count%>)"
		},
		tooltip: {
			formatter: function() {
				return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage) +' %';
			}
		},
		plotOptions: {
			pie: {
				allowPointSelect: true,
				cursor: 'pointer',
				dataLabels: {
					enabled: true,
					color: '#000000',
					connectorColor: '#000000',
					formatter: function() {
						return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage) +' %';
					}
				}
			}
		},
		series: [{
			type: 'pie',
			name: 'Browser share',
			data: [
				
				<% @gp_data.each_pair do |k,v| %>
				 <%= "['#{k}', #{v}]," %>
				<% end %>
			]
		}]
	});
	tw_chart = new Highcharts.Chart({
		chart: {
			renderTo: 'tw_chart',
			plotBackgroundColor: null,
			plotBorderWidth: null,
			plotShadow: false
		},
		title: {
			<% 
				count =0 
				@tw_data.each_pair do |k,v|
 
			%>
			<% count += v %>
			<% end %>
			text: "Usage by Companies on Twitter (Total: <%=count%>)"
		},
		tooltip: {
			formatter: function() {
				return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage) +' %';
			}
		},
		plotOptions: {
			pie: {
				allowPointSelect: true,
				cursor: 'pointer',
				dataLabels: {
					enabled: true,
					color: '#000000',
					connectorColor: '#000000',
					formatter: function() {
						return '<b>'+ this.point.name +'</b>: '+ Math.round(this.percentage) +' %';
					}
				}
			}
		},
		series: [{
			type: 'pie',
			name: 'Browser share',
			data: [
				
				<% @tw_data.each_pair do |k,v| %>
				 <%= "['#{k}', #{v}]," %>
				<% end %>
			]
		}]
	});
});

		</script>
	</head>
	<body>
<script type="text/javascript" src="javascripts/highcharts.js"></script>

<div id="chart" style="width: 800px; height: 400px; margin: 0 auto"></div>
<div id="fb_chart" style="width: 800px; height: 400px; margin: 0 auto"></div>
<div id="gp_chart" style="width: 800px; height: 400px; margin: 0 auto"></div>
<div id="tw_chart" style="width: 800px; height: 400px; margin: 0 auto"></div>

	</body>
</html>

app/views/companies/_companies.html.erb
<table id="hor-zebra" >
  <thead>
  <tr>
    <th scope="col"><%= sortable "name" %></th>
    <th scope="col"><%= sortable "domain" %></th>
    <th scope="col"><%= sortable "qrank" %></th>
    <th scope="col"><%= sortable "arank" %></th>
    <th scope="col"><%= sortable "server_location", "Server Location" %></th>
    <th scope="col"><%= sortable "deepdive" %></th>
    <th scope="col"><%= sortable "chat" %></th>
    <th scope="col"><%= sortable "is_brand", "Is Brand" %></th>
    <th scope="col"><%= sortable "retailers" %></th>
    <th scope="col"><%= sortable "social" %></th>
    <th scope="col"></th>
    <th scope="col"></th>
    <th scope="col"></th>
  </tr>
  </thead>

<% i=0 %>
<% @companies.each do |company| %>
  <% if i%2==0 %>
	<tr>
  <% else %>
	<tr class="odd">
  <% end %>
    <td style="max-width:250px;word-wrap:break-word;"><%= company.name %></td>
    <td><a href="http://www.<%= company.domain %>"><%= company.domain %></a></td>
    <td><%= company.qrank %></td>
    <td><%= company.arank %></td>
    <td><%= company.server_location %></td>
    <td style="max-width:250px;word-wrap:break-word;"><a href="http://www.<%= company.deepdive %>"><%= company.deepdive %></a></td>
    <td><%= company.chat %></td>
    <td><%= company.is_brand %></td>
    <td><%= company.retailers %></td>
    <td><% company.social.each do |s| %>
	   <a href='<%=s%>'><%=s%></a><br/>
	<% end %>
    </td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
  <% i = i+1 %>
<% end %>
</table>

<br />
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= paginate @companies %>

<%= link_to 'New Company', new_company_path %>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :domain %><br />
    <%= f.text_field :domain %>
  </div>
  <div class="field">
    <%= f.label :qrank %><br />
    <%= f.number_field :qrank %>
  </div>
  <div class="field">
    <%= f.label :arank %><br />
    <%= f.number_field :arank %>
  </div>
  <div class="field">
    <%= f.label :server_location %><br />
    <%= f.text_field :server_location %>
  </div>
  <div class="field">
    <%= f.label :deepdive %><br />
    <%= f.text_field :deepdive %>
  </div>
  <div class="field">
    <%= f.label :is_brand %><br />
    <%= f.check_box :is_brand %>
  </div>
  <div class="field">
    <%= f.label :retailers %><br />
    <%= f.text_field :retailers %>
  </div>
  <div class="field">
    <%= f.label :social %><br />
    <%= f.text_field :social %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Companies</h1>


<%= form_tag companies_path, :method => 'get', :id => "companies_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>

  <div id="companies"><%= render 'companies' %></div>
<% end %>

app/views/companies/index.js.erb
$("#companies").html("<%= escape_javascript(render("companies")) %>");

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @company.name %>
</p>

<p>
  <b>Domain:</b>
  <a href="<%= @company.domain %>"><%= @company.domain %></a>
</p>

<p>
  <b>Qrank:</b>
  <%= @company.qrank %>
</p>

<p>
  <b>Arank:</b>
  <%= @company.arank %>
</p>

<p>
  <b>Server location:</b>
  <%= @company.server_location %>
</p>

<p>
  <b>Deepdive:</b>
  <%= @company.deepdive %>
</p>

<p>
  <b>Chat:</b>
  <%= @company.chat %>
</p>

<p>
  <b>Is brand:</b>
  <%= @company.is_brand %>
</p>

<p>
  <b>Retailers:</b>
  <%= @company.retailers %>
</p>

<p>
  <b>Social:</b>
  <%= @company.social %>
</p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatid</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <LINK href="stylesheets/style.css" rel="stylesheet" type="text/css">
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/retailers/_form.html.erb
<%= form_for(@retailer) do |f| %>
  <% if @retailer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@retailer.errors.count, "error") %> prohibited this retailer from being saved:</h2>

      <ul>
      <% @retailer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :brands %><br />
    <%= f.text_field :brands %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/retailers/edit.html.erb
<h1>Editing retailer</h1>

<%= render 'form' %>

<%= link_to 'Show', @retailer %> |
<%= link_to 'Back', retailers_path %>

app/views/retailers/index.html.erb
<h1>Listing retailers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th>Brands</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @retailers.each do |retailer| %>
  <tr>
    <td><%= retailer.name %></td>
    <td><%= retailer.url %></td>
    <td><%= retailer.brands %></td>
    <td><%= link_to 'Show', retailer %></td>
    <td><%= link_to 'Edit', edit_retailer_path(retailer) %></td>
    <td><%= link_to 'Destroy', retailer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Retailer', new_retailer_path %>

app/views/retailers/new.html.erb
<h1>New retailer</h1>

<%= render 'form' %>

<%= link_to 'Back', retailers_path %>

app/views/retailers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @retailer.name %>
</p>

<p>
  <b>Url:</b>
  <%= @retailer.url %>
</p>

<p>
  <b>Brands:</b>
  <%= @retailer.brands %>
</p>


<%= link_to 'Edit', edit_retailer_path(@retailer) %> |
<%= link_to 'Back', retailers_path %>

app/views/search/index.html.erb
<h1>Retailer Search</h1>
<%= form_tag('/search' , :method => 'get') do %>
  <p>Enter Brand: 
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<% @results.each do |result| %>
<p> 
	<%= result %>
</p>
<% end %>

<% if !@hit_count.nil? %>
<%= "No of results: "+@hit_count  %>
<% end %>